### ISSUE TITLE
Not starting; importlib.metadata.PackageNotFoundError

### ISSUE THREAD

**Issue by mxmilkiib** [Lawrence-Chiappelli/screendimmer#12]
```
02:47:23 milk@red:~ % screendimmer
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/screendimmer", line 33, in <module>
    sys.exit(load_entry_point('screendimmer==0.4.2', 'gui_scripts', 'screendimmer')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/screendimmer", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for screendimmer
```

I have `extra/python-importlib-metadata 5.1.0-2 (40.3 KiB 186.7 KiB) (Installed)`.

**Comment by T-3B** [comment]
If you are using it from the AUR, you should probably rebuild it as some deps might have updated (see `checkrebuild`).
