### ISSUE TITLE
Fails to start when any screen is a clone of another

### ISSUE THREAD

**Issue by mxmilkiib** [Lawrence-Chiappelli/screendimmer#3]
```
Exception caught initializing the UI:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/screendimmer/tray.py", line 32, in __init__
    self.init_ui()
  File "/usr/lib/python3.10/site-packages/screendimmer/tray.py", line 41, in init_ui
    self._apply_connections()
  File "/usr/lib/python3.10/site-packages/screendimmer/tray.py", line 181, in _apply_connections
    [(i, monitor.triggered.connect(self._switch_monitor_func(i))) for i, monitor in enumerate(self.monitors)]
  File "/usr/lib/python3.10/site-packages/screendimmer/tray.py", line 181, in <listcomp>
    [(i, monitor.triggered.connect(self._switch_monitor_func(i))) for i, monitor in enumerate(self.monitors)]
  File "/usr/lib/python3.10/site-packages/screendimmer/tray.py", line 251, in _switch_monitor_func
    return switcher[index]
KeyError: 3
```

**Comment by Lawrence-Chiappelli** [comment]
Appreciate the error report and thank you for the opening this issue. I will take into account cloned monitors in the next update.
